name: Generate GitHub Contributions

permissions:
  contents: write

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Fetch contributions
        run: |
          mkdir -p assets/data

          curl -s -X POST https://api.github.com/graphql \
            -H "Authorization: Bearer ${{ secrets.THESECRETALSOPRANAB }}" \
            -H "Content-Type: application/json" \
            -d '{
              "query": "query ($login: String!) { user(login: $login) { contributionsCollection { contributionCalendar { weeks { contributionDays { date contributionCount } } } } } }",
              "variables": { "login": "alsopranab" }
            }' > response.json

          jq -s '
          [
            .[0].data.user.contributionsCollection.contributionCalendar.weeks[]
            .contributionDays[]
            | { date: .date, count: .contributionCount }
          ]
          ' response.json > assets/data/contributions.json

      - name: Commit data
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add assets/data/contributions.json
          git commit -m "Update GitHub contributions" || echo "No changes"
          git push
